In [1]:
DATABASE = "postgres"
USER = "postgres"
PASSWORD = "postgres"
HOST = "localhost"
PORT = "5432"

In [2]:
from math import ceil
from sqlalchemy import create_engine
from datetime import date
from hashlib import sha3_512
import psycopg2
import multiprocessing
import traceback
import pandas as pd
import json
import boto3
import os

In [4]:
print(f"Process {os.getpid()} Establishing Connection to DB")
db = create_engine(f"postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}")
conn = db.connect()
print(f"Process {os.getpid()} Successfully Connected to DB")

Process 48736 Establishing Connection to DB
Process 48736 Successfully Connected to DB

In [18]:
query = """select * from user_logins"""

In [20]:
pd.read_sql(query, conn)

,user_id,device_type,masked_ip,masked_device_id,locale,app_version,create_date
0,None,None,None,None,None,NaN,2023-09-21
1,None,None,None,None,None,NaN,2023-09-21
2,None,None,None,None,None,NaN,2023-09-21
3,None,None,None,None,None,NaN,2023-09-21
4,None,None,None,None,None,NaN,2023-09-21
...,...,...,...,...,...,...,...
767,92d8ceec-2e12-49f3-81bd-518fe66971ec,android,50feb83841f8422bb6018dae0acfdf2a69e95853c60eef...,a7ce8240c05f6391fdf8fb192da3cce27965989b953beb...,BR,NaN,2023-09-21
768,92d8ceec-2e12-49f3-81bd-518fe66971ec,android,50feb83841f8422bb6018dae0acfdf2a69e95853c60eef...,a7ce8240c05f6391fdf8fb192da3cce27965989b953beb...,BR,NaN,2023-09-21
769,92d8ceec-2e12-49f3-81bd-518fe66971ec,android,50feb83841f8422bb6018dae0acfdf2a69e95853c60eef...,a7ce8240c05f6391fdf8fb192da3cce27965989b953beb...,BR,NaN,2023-09-21
770,92d8ceec-2e12-49f3-81bd-518fe66971ec,android,50feb83841f8422bb6018dae0acfdf2a69e95853c60eef...,a7ce8240c05f6391fdf8fb192da3cce27965989b953beb...,BR,NaN,2023-09-21
771,92d8ceec-2e12-49f3-81bd-518fe66971ec,android,50feb83841f8422bb6018dae0acfdf2a69e95853c60eef...,a7ce8240c05f6391fdf8fb192da3cce27965989b953beb...,BR,NaN,2023-09-21